baseURL = "https://webwriterscollective.com/"
locale = "en-GB"
title = "Web Writers’ Collective"
theme = "webwriterscollective"

[taxonomies]
  tag = "tags"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
